
services:
  postgres:
    image: postgres:15-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-marketplace_dev}
      POSTGRES_USER: ${POSTGRES_USER:-marketplace_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-marketplace_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - marketplace-network

  # redis:
  #   image: redis:7-alpine
  #   container_name: marketplace-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - marketplace-network

volumes:
  postgres_data:
  redis_data:

networks:
  marketplace-network:
    driver: bridge