name: recicar-marketplace
services:
  - name: recicar-app
    image: recicar-marketplace:latest
    ports:
      - port: 8080
        http:
          paths:
            - path: /
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: prod
      - name: DATABASE_URL
        value: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
      - name: DATABASE_USERNAME
        secret: DATABASE_USERNAME
      - name: DATABASE_PASSWORD
        secret: DATABASE_PASSWORD
      - name: DATABASE_HOST
        secret: DATABASE_HOST
      - name: DATABASE_PORT
        value: "5432"
      - name: DATABASE_NAME
        secret: DATABASE_NAME
    resources:
      cpu: 1000m
      memory: 1Gi
    healthcheck:
      http:
        path: /actuator/health
        port: 8080
      initial_delay: 30
      period: 10
      timeout: 5
      retries: 3
