# Northflank deployment configuration for Recicar Marketplace
# This file defines the deployment configuration for Northflank

version: 1

services:
  recicar-marketplace:
    type: service
    image:
      type: dockerfile
      dockerfilePath: ./Dockerfile
      context: .
    
    # Resource allocation
    resources:
      cpu: 1000m
      memory: 1Gi
    
    # Port configuration
    ports:
      - port: 8080
        protocol: http
        public: true
    
    # Environment variables for production
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}
      - DATABASE_USERNAME=${USERNAME}
      - DATABASE_PASSWORD=${PASSWORD}
      - SERVER_PORT=8080
    
    # Health check configuration
    healthCheck:
      type: http
      path: /actuator/health
      port: 8080
      initialDelay: 30
      period: 10
      timeout: 5
      retries: 3
    
    # Scaling configuration
    scaling:
      minReplicas: 1
      maxReplicas: 3
      targetCPU: 70
      targetMemory: 80
    
    # Restart policy
    restartPolicy:
      type: always
      maxRetries: 3
    
    # Logging configuration
    logging:
      level: INFO
      format: json
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
