-- Part 2: more makes; combined with V14 and V20 gives a large navigable set (200+ is a data-import goal; expand as needed)
INSERT INTO brands (name, slug, country, description) VALUES
('Genesis', 'genesis', 'South Korea', 'Hyundai premium'),
('Daimler', 'daimler', 'United Kingdom', 'Historic marque'),
('Donkervoort', 'donkervoort', 'Netherlands', 'Hand-built'),
('Eagle', 'eagle', 'United States', 'Chrysler brand'),
('FSO', 'fso', 'Poland', 'Polski Fiat / Polonez'),
('GMC', 'gmc', 'United States', 'GM truck brand'),
('Koenigsegg', 'koenigsegg', 'Sweden', 'Hypercar'),
('KTM', 'ktm', 'Austria', 'X-Bow and sport'),
('LDV', 'ldv', 'China', 'Van brand'),
('Lincoln', 'lincoln', 'United States', 'Ford premium'),
('LYNK and CO', 'lynk-and-co', 'China', 'Geely'),
('Mahindra', 'mahindra', 'India', 'Multi sector'),
('Maruti', 'maruti', 'India', 'Maruti Suzuki'),
('Maxus', 'maxus', 'China', 'SAIC commercial'),
('Maybach', 'maybach', 'Germany', 'Mercedes ultra luxury'),
('Mercury', 'mercury', 'United States', 'Historic Ford'),
('Moskwitsch', 'moskwitsch', 'Russia', 'Historic'),
('NSU', 'nsu', 'Germany', 'Audi historic'),
('Oldsmobile', 'oldsmobile', 'United States', 'Historic GM'),
('Pagani', 'pagani', 'Italy', 'Supercars'),
('Piaggio', 'piaggio', 'Italy', 'Commercial and micro'),
('Plymouth', 'plymouth', 'United States', 'Chrysler historic'),
('Puch', 'puch', 'Austria', 'Historic and micro'),
('Ravon', 'ravon', 'Uzbekistan', 'GM JV'),
('Renault Trucks', 'renault-trucks', 'France', 'Commercial'),
('Rolls-Royce', 'rolls-royce', 'United Kingdom', 'Ultra luxury'),
('RUF', 'ruf', 'Germany', 'Porsche tuner'),
('Scion', 'scion', 'United States', 'Toyota US youth (historic)'),
('Spyker', 'spyker', 'Netherlands', 'Sports and aviation'),
('Steyr', 'steyr', 'Austria', 'Commercial and historic'),
('StreetScooter', 'streetscooter', 'Germany', 'Electric last mile'),
('Talbot', 'talbot', 'United Kingdom', 'Historic'),
('TVR', 'tvr', 'United Kingdom', 'Sports car'),
('Trabant', 'trabant', 'Germany', 'East Germany historic'),
('Triumph', 'triumph', 'United Kingdom', 'Classic'),
('Vauxhall VXR', 'vauxhall-vxr', 'United Kingdom', 'Performance sub-brand'),
('Wartburg', 'wartburg', 'Germany', 'East Germany'),
('Wiesmann', 'wiesmann', 'Germany', 'Hand-built'),
('Yugo', 'yugo', 'Serbia', 'Zastava export'),
('Zastava', 'zastava', 'Serbia', 'Yugo parent'),
('Pininfarina', 'pininfarina', 'Italy', 'Battista and design'),
('Panther', 'panther', 'United Kingdom', 'Low volume'),
('Reliant', 'reliant', 'United Kingdom', 'Historic three-wheelers'),
('Innocenti', 'innocenti', 'Italy', 'Historic small'),
('Glas', 'glas', 'Germany', 'BMW history'),
('Goliath', 'goliath', 'Germany', 'Borgward historic')
ON CONFLICT (slug) DO NOTHING;
